
services:
  bd_pf:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: BODY_PERFORMANCE


#  test:
#    build: .
#    container_name: Coches_Regresion_ML-TEST
#    environment:
#      - LOG_FILE=/log.txt
#      - PYTHONPATH=/app/regression  # Agregar la ruta del código fuente
#    volumes:
#      - .:/app
#    command: pytest regression/tests
    